apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c6u117a67-go 
  janus-idp.io/tekton: c6u117a67-go
  backstage.io/kubernetes-id: c6u117a67-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c6u117a67-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  