apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c6u117a67-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c6u117a67-go 
  name: c6u117a67-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c6u117a67-go 
