apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: c6u117a67-go-gitops
  description: This is GitOps manifest for c6u117a67-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: c6u117a67-go
    janus-idp.io/tekton: c6u117a67-go 
    backstage.io/kubernetes-id: c6u117a67-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:c6u117a67-go
